/Mode Full
/Geometry/Gretina/detector/enableCapsules
/Geometry/Gretina/detector/enableCryostats
/Geometry/Gretina/Shell Greta
/Geometry/ChicoX/Construct
/Geometry/Target/Construct
/Geometry/Target/StandardTarget 208Pb
/Geometry/Target/Thickness 0.40 um
#
/Reaction/ProjectileZ 62
/Reaction/ProjectileA 148
/Reaction/RecoilZ 82
/Reaction/RecoilA 208
/Reaction/AddThetaLAB 16 deg
/Reaction/AddThetaLAB 177 deg
/Reaction/OnlyProjectiles
#/Reaction/OnlyRecoils
#/Reaction/Optimize
#
#/Beam/Energy 658 MeV
/Beam/Energy 526 MeV
/Beam/SigmaEn 1.2 MeV
#/Beam/SigmaAX 0.0 deg
#/Beam/SigmaAY 0.0 deg
#/Beam/PositionX -1.2 mm
#/Beam/PositionY 0.5 mm
/Beam/SigmaX 1.1 mm
/Beam/SigmaY 1.1 mm
#
/Excitation/Projectile/LevelScheme sm148.lvl
/Excitation/Projectile/Probabilities sm148_on_pb208_LE.prb
/Excitation/Projectile/StatisticalTensors sm148_on_pb208_LE.ten
#/Excitation/Projectile/OnlyConsiderState 1
/Excitation/Recoil/LevelScheme pb208.lvl
/Excitation/Recoil/Probabilities pb208_by_sm148_LE.prb
/Excitation/Recoil/StatisticalTensors pb208_by_sm148_LE.ten
#/Excitation/Recoil/OnlyConsiderState 1
#
/Output/FileName full.dat
/Output/OnlyWriteCoincidences
/Output/WriteDiagnostics
/Output/DiagnosticsFileName info.dat
#
/run/numberOfThreads 6
/run/beamOn 100000
